import {
  DesktopOutlined,
  AppstoreOutlined,
  CalendarOutlined,
  ContactsOutlined,
  DashboardOutlined,
  FileDoneOutlined,
  PieChartOutlined,
  SolutionOutlined,
  UserOutlined,
  FolderOutlined,
  RocketOutlined,
  AreaChartOutlined,
  PoundOutlined,
  BookOutlined,
  BarChartOutlined,
  ControlOutlined,
  AuditOutlined,
  BgColorsOutlined,
  GoldOutlined,
  FundProjectionScreenOutlined,
  InteractionOutlined,
  HomeOutlined,
} from '@ant-design/icons';

const Icon = {
  desktop: <DesktopOutlined style={{ fontSize: 16 }} />,
  appstore: <AppstoreOutlined style={{ fontSize: 16 }} />,
  calendar: <CalendarOutlined style={{ fontSize: 16 }} />,
  contacts: <ContactsOutlined style={{ fontSize: 16 }} />,
  'bar-chart': <DashboardOutlined style={{ fontSize: 16 }} />,
  dashboard: <DashboardOutlined style={{ fontSize: 16 }} />,
  'file-done': <FileDoneOutlined style={{ fontSize: 16 }} />,
  'pie-chart': <PieChartOutlined style={{ fontSize: 16 }} />,
  solution: <SolutionOutlined style={{ fontSize: 16 }} />,
  user: <UserOutlined style={{ fontSize: 16 }} />,
  folder: <FolderOutlined style={{ fontSize: 16 }} />,
  rocket: <RocketOutlined style={{ fontSize: 16 }} />,
  'area-chart': <AreaChartOutlined style={{ fontSize: 16 }} />,
  pound: <PoundOutlined style={{ fontSize: 16 }} />,
  book: <BookOutlined style={{ fontSize: 16 }} />,
  controlOutlined: <ControlOutlined style={{ fontSize: 16 }} />,
  audit: <AuditOutlined style={{ fontSize: 16 }} />,
  product: <HomeOutlined style={{ fontSize: 16 }} />,
  goods: <GoldOutlined style={{ fontSize: 16 }} />,
  fundProjectionScreenOutlined: <FundProjectionScreenOutlined style={{ fontSize: 16 }} />,
  interactionOutlined: <InteractionOutlined style={{ fontSize: 16 }} />,
};

export default Icon;
